timezone: Europe/Paris

base_packages:
  - curl
  - git
  - vim
  - ufw
  - fail2ban
  - chrony

ssh_port: 22
ssh_allow_tcp_forwarding: "no"
ssh_max_auth_tries: 3
ssh_login_grace_time: 30
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_allowed_users:
  - ubuntu
  - admin
  - root
  - deploy
