---
all:
  children:
    env_prod:
      hosts:
        bastion:
        observability:
        applicatif:
        netbox:

    env_staging:
      hosts:
        preprod:

    cap_observability:
      children:
        env_prod:
        env_staging:

    cap_monitoring_central:
      hosts:
        observability:
    # preprod: