---
# local.yml — Main entry point playbook
# Run with: ansible-playbook local.yml

- name: "Configure servers"
  hosts: all
  gather_facts: true
  become: true
  force_handlers: true

  roles:
  
    # - role: bootstrap2
    #   when: "'env_staging' in group_names"
    
    - role: system_baseline

    - role: ssh_hardening

    - role: host_firewall
