name: CI - Iac Validation

on:
  push:
    branches: ["**"]
    paths:
      - "infra/**"
      - "ansible/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "infra/**"
      - "ansible/**"
      - ".github/workflows/ci.yml"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      infra: ${{steps.filter.outputs.infra}}
      ansible: ${{steps.filter.outputs.ansible}}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            infra:
              - 'infra/**'
            ansible:
              - 'ansible/**'
  terraform:
    needs: changes
    if: ${{needs.changes.outputs.infra == 'true'}}
    name: Terraform Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Install TFLint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: tflint --recursive

      - name: Run TFSec (Security)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infra

  ansible:
    needs: changes
    if: ${{needs.changes.outputs.ansible == 'true'}}
    name: Ansible Checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ansible

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible and Lint Tools
        run: |
          pip install ansible ansible-lint yamllint

      - name: Run YAML Lint
        run: yamllint .

      - name: Run Ansible Lint
        run: ansible-lint .
